### ISSUE TITLE
Roadmap for future features.

### ISSUE THREAD

**Issue by Xithrius** [Xithrius/dev-twitch-tui-chat#5]
- [ ] Scrolling: #4 
- [ ] Color the TUI user when they speak. Color can come from an environment variable.
- [ ] Log into multiple chats, tab through them with `ctrl + tab` to cycle right in the tabs and `ctrl + shift + tab` to cycle left.
- [ ] Considering unit testing in the future.
- [ ] Seeing who's in chat.
- [ ] Document everything.
- [ ] GitHub Workflows.
- [ ] Precommit.
- [ ] Dependabot.
